# 防止已经绑定过的QQ重新绑定
prevent_qq_rebind: true
# 群内申请白名单的命令前缀
bind_command_prefix: 申请白名单
# 群内查询玩家绑定QQ的命令前缀
select_player_command_prefix: 查询玩家绑定
# 群内查询QQ绑定玩家的命令前缀
select_qq_command_prefix: 查询QQ绑定
# 用于白名单绑定的机器人
used_bot_accounts:
- 123456
- 789012
# 用于白名单绑定的群聊
used_groups:
- 123456
- 789012
# 白名单模式,1为不允许玩家进入的模式,2为允许玩家进入参观一段时间的模式
whitelist_mode: 1
# 白名单模式2下允许玩家参观的时间
mode_2_allow_visit_second: 600
# 白名单模式2下参观者发言的间隔,单位为秒
mode_2_visitor_chat_cd: 10
# 白名单模式2下给参观者提示绑定白名单的间隔,单位为秒
mode_2_hint_cd: 30
# 检测玩家是否在群内
check_qq_in_group: true
# 玩家退群时删除白名单
remove_bind_when_qq_quit: false
code_timeout_second: 300
messages:
  placeholder:
    visitor_tag: '&a[参观玩家]'
  command:
    player_only: '&a此命令只允许玩家使用'
    reload: '&a已重载Whitelist4QQ'
    remove:
      usage: '&c用法：/whitelist4qq remove <玩家名>'
      success: '&a已移除指定玩家的绑定！'
    bind:
      bound: '&a您已经绑定过，无需再次绑定'
      wait: '&a您的绑定码为%code%，请在群内使用“申请白名单%code%”进行申请'
      bind: '&a您已绑定%qq%，现在你可以游玩本服务器了！'
    get_bind:
      invalid_qq: '&c请输入有效的qq号'
      selecting: '&a&l正在查找绑定中'
      not_exist: '&a查询完成，此QQ没有绑定玩家'
      success: '&a查询完成，%qq%绑定的玩家为%player%'
      hover: '&a点击复制名字'
    get_qq:
      invalid_player: '&c此玩家未在服务器注册过'
      selecting: '&a&l正在查找绑定中'
      not_exist: '&a查询完成，此玩家没有绑定QQ'
      success: '&a查询完成，%player%绑定的QQ为%qq%'
      hover: '&a点击复制QQ'
  kick_message:
    mode_1: |-
      &c你不在本服的白名单中，请加入我们的QQ群123456进行申请
      &c申请方式：在群内发送“申请白名单%code%”
      &c有效时长5分钟
    mode_2: |-
      &c你不在本服的白名单中并且你已经用完你的参观时间，请加入我们的QQ群123456进行白名单申请
      &c申请方式：在群内发送“申请白名单%code%”
      &c有效时长5分钟
    not_in_group: '&c你不在本服的群中，无法加入服务器'
  bot_message:
    bind_success: 您已成功绑定玩家%player%，现在你可以游玩本服务器了！
    bind_failed:
      not_exist_code: 不存在此绑定码
      bound: 你已经绑定了一个游戏账号%player%，无法重复绑定
    
    select_qq_failed:
      number_format: 查询错误，你查询的内容并不是一个QQ号
      not_exist: 查询完成，不存在此QQ绑定的玩家
    select_qq_success: 查询完成，此QQ绑定的玩家为%player%
    select_player_failed_not_exist: 查询完成，此玩家没有绑定QQ号
    select_player_success: 查询完成，该玩家绑定的QQ为%qq%
  mode_2_bind_hint_message: '&a如果您觉得我们服务器不错,可以使用命令/bind申请白名单噢'
  visitor_chat_in_cd: '&c您当前只能每10秒发送一条消息'
