# 防止已经绑定过的QQ重新绑定
prevent_qq_rebind: true
# 群内申请白名单的命令前缀
bind_command_prefix: 申请白名单
# 群内查询玩家绑定QQ的命令前缀
select_player_command_prefix: 查询玩家绑定
# 群内查询QQ绑定玩家的命令前缀
select_qq_command_prefix: 查询QQ绑定
# 用于白名单绑定的机器人
used_bot_accounts:
- 123456
- 789012
# 用于白名单绑定的群聊
used_groups:
- 123456
- 789012
# 白名单模式,1为不允许玩家进入的模式,2为允许玩家进入参观一段时间的模式
whitelist_mode: 1
# 白名单模式2下允许玩家参观的时间
mode_2_allow_visit_second: 600
# 白名单模式2下参观者发言的间隔,单位为秒
mode_2_visitor_chat_cd: 10
# 白名单模式2下给参观者提示绑定白名单的间隔,单位为秒
mode_2_hint_cd: 30
# 检测玩家是否在群内
check_qq_in_group: true
# 玩家退群时删除白名单
remove_bind_when_qq_quit: false
code_timeout_second: 300
#数据相关设置
data:
  type: mysql
  mysql:
    driver: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/group'
    username: root
    password: 123456
    table: whitelist4qq
    hikari:
      connection-timeout: 3000
      min-idle: 10
      max-life-time: 3000
      max-pool-size: 50
      auto-commit: true
messages:

