name: Whitelist4QQ
main: com.github.yufiriamazenta.whitelist4qq.Whitelist4QQ
authors:
  - YufiriaMazenta
version: '${version}'
description: Whitelist for QQ with MiraiMC.
api-version: 1.15
folia-supported: true
depend:
  - MiraiMC
permissions:
  whitelist4qq.*:
    default: op
    children:
      whitelist4qq.command.*:
        default: op
        children:
          whitelist4qq.command:
            description: Allow use /whitelist4qq
            default: true
          whitelist4qq.command.reload:
            default: op
            description: Allow use /whitelist4qq reload
          whitelist4qq.command.remove:
            default: op
            description: Allow use /whitelist4qq remove
